server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: keynote-service
          uri: lb://keynote-service
          predicates:
            - Path=/keynotes/**
        - id: conference-service
          uri: lb://conference-service
          predicates:
            - Path=/conferences/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/conference-realm
          jwk-set-uri: http://keycloak:8080/realms/conference-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
